account/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('account/', views.own_account, name='account'),
    # path('account/edit_account', views.edit_account, name='edit_account'),
    path('account/change_password', views.change_password, name='change_password'),
]

cart/urls.py
from django.urls import path
from django.conf.urls.static import static
from . import views as v
from django.conf import settings
from cart import views as views_cart

urlpatterns = [
    path('my_cart/', views_cart.cart_display, name='cart'),
    path('add/<id>', v.cart_add, name='add'),
    path('remove/<id>', v.cart_remove, name='remove'),
    path('delete_all/', v.remove_all_cart, name='delete_all'),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

toy_store/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('accounts/', include('account.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls')),
    path('receipt/', include('receipt.urls')),
]

cart/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=150)

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "password1", "password2"]


class EditAccountForm(UserChangeForm):
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]

cart/forms.py
from django import forms

# PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 20)]


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(required=True)
    # quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

receipt/forms.py
from django import forms


class DeliveryForm(forms.Form):
    phone = forms.CharField(max_length=200)
    address = forms.CharField(max_length=200)

account/views.py
import logging
import sys

from django.shortcuts import render, redirect
from .forms import SignUpForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from receipt.models import Receipt, ReceiptHasToy

LOGGING = {
    'version': 1,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
        }
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO'
    }
}
logging.config.dictConfig(LOGGING)


def signup(response):
    if response.method == "POST":
        form = SignUpForm(response.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(response, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(response, 'signup.html', {"form": form})


def change_password(response):
    if response.method == "POST":
        form = PasswordChangeForm(data=response.POST, user=response.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(response, form.user)
            return redirect('/accounts/account')
        else:
            return redirect('/accounts/account/change_password')
    else:
        form = PasswordChangeForm(user=response.user)
    return render(response, 'change_password.html', {"form": form})


def own_account(request):
    user = request.user
    receipts = Receipt.objects.raw("SELECT * FROM receipt_receipt WHERE user_id = %s", [user.id])
    dict_receipts = {}
    for receipt in receipts:
        one_id = receipt.id
        one_receipt = Receipt.objects.raw("SELECT * FROM receipt_receipt WHERE id = %s", [one_id])[0]
        dict_receipts[one_receipt] = []
        receipt_toy = ReceiptHasToy.objects.raw("SELECT *  FROM receipt_receipthastoy JOIN product_toy ON "
                                                "receipt_receipthastoy.toy_id = product_toy.id "
                                                "WHERE receipt_receipthastoy.receipt_id = %s", [one_receipt.id])
        for position in receipt_toy:
            dict_receipts[one_receipt].append(position)
    return render(request, 'account.html', {'receipts': receipts, 'dict_receipts': dict_receipts, 'user': user})

cart/views.py
import logging
import logging.config
import sys

from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST

from product.models import Toy
from .cart import Cart
from .forms import CartAddProductForm

LOGGING = {
    'version': 1,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
        }
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO'
    }
}
logging.config.dictConfig(LOGGING)


@require_POST
def cart_add(request, id):
    cart = Cart(request)
    logging.info(cart)
    # toy = get_object_or_404(Toy, id=id)
    toy = Toy.objects.raw("SELECT * FROM product_toy WHERE id = %s", [id])[0]
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(toy=toy, quantity=cd['quantity'], update_quantity=cd['update'])
        toy_id = str(toy.id)
        if cart.cart[toy_id]['quantity'] > toy.count:
            cart.cart[toy_id]['quantity'] = toy.count
    return redirect('cart')


def cart_remove(request, id):
    cart = Cart(request)
    # toy = get_object_or_404(Toy, id=id)
    toy = Toy.objects.raw("SELECT * FROM product_toy WHERE id = %s", [id])[0]
    cart.remove(toy)
    return redirect('cart')


def remove_all_cart(request):
    cart = Cart(request)
    cart.clear()
    return redirect('cart')


def cart_display(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
        logging.info(item['update_quantity_form'])
    return render(request, 'cart.html', {'cart': cart})

templates/account.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Account{% endblock %}

{% block content %}
<aside>
    <div class="container">
    <div class="row">
    <section>
        <div class="col-2">

          <h4>Name: {{ user.first_name }}</h4>
            <h4>Surname: {{ user.last_name }}</h4>
            <h4>Username: {{ user.username }}</h4>
            <a class="btn" href = "{% url 'change_password' %}">Change Password</a>

        </div>
    </section>
        <section>
            <div class="col-2">
                {% for receipt, list in dict_receipts.items %}
            <div class="form-container-orders">
            <h4>Order number: {{ receipt.id }}</h4>
{#            {% if receipt.status == "Accepted" %}#}
{#            <a href="{% url 'cancel' receipt.id %}"><img src="{% static 'images/cancel.jpg' %}" width="30px"#}
{#                                                         height="50px" /></a>#}
{#            {% endif %}#}
{#            <p>{{receipt.toy.name}} x {{receipt.count}}</p>#}
                {% for i in list %}
            <p>{{ i.count }} x {{ i.name }}</p>
                    {%  endfor  %}
            <p> Status: {{receipt.status}}</p>
            <p> $ {{receipt.amount}}</p>
            </div>
                {% endfor %}
            </div>

        </section>
        </div>
    </div>
</aside>
{% endblock %}

templates/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Toy store</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,200&display=swap"
      rel="stylesheet"
    />
    <link
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            rel="stylesheet"
    />
  </head>
  <body>
    <div class="header">
      <div class="container">
        <div class="navbar">
          <div class="logo">
            <a href="{% url 'home' %}">
              <img src="{%  static 'images/logo.png' %}" alt="" width="125px"
            /></a>
          </div>
          <nav>
            <ul id="MenuItems">
              <li><a href="{% url 'home' %}">Home</a></li>
              <li><a href="{% url 'catalog' %}">Catalog</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'account' %}">Account</a></li>
                    <li><a href="{% url 'logout' %}">Log Out</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Log In</a></li>
                    <li><a href="{% url 'signup' %}">Sign Up</a></li>
                {% endif %}
            </ul>
          </nav>
            {% if user.is_authenticated %}
          <a href="{% url 'cart' %}"
            ><img src="{% static 'images/cart.png' %}" alt="" width="30px" height="30px"
          /></a>{% endif %}
          <img
            src="{% static 'images/menu.png' %}"
            alt=""
            class="menu-icon"
            onclick="menutoggle()"
          />
        </div>
      </div>
    </div>
    <!-- Navigation ends here -->
  {% block content %}
    {% endblock %}
 <!-- Footer -->
    <div class="footer">
      <div class="container">
        <div class="row">
          <div class="footer-col-1">
            <h3>Download Our App</h3>
            <p>
              Download App for Android <br />
              and ios mobile phone
            </p>
            <div class="app-logo">
              <img src="{% static 'images/play-store.png' %}" alt="" />
              <img src="{% static 'images/app-store.png' %}" alt="" />
            </div>
          </div>
          <div class="footer-col-2">
            <img src="{% static 'images/logo-white.png' %}" alt="" />
            <p>
              Lorem, ipsum dolor sit amet consectetur <br />adipisicing elit.
              Porro, eum?
            </p>
          </div>
          <div class="footer-col-3">
            <h3>Useful Links</h3>
            <ul>
              <li>Coupons</li>
              <li>Blog Post</li>
              <li>Return Policy</li>
              <li>Join Affiliate</li>
            </ul>
          </div>

          <div class="footer-col-4">
            <h3>Follow us</h3>
            <ul>
              <li>Facebook</li>
              <li>Twitter</li>
              <li>Instagram</li>
              <li>YouTube</li>
            </ul>
          </div>
        </div>
        <hr />
        <p class="copyright">Copyright 2020 - introidx</p>
      </div>
    </div>
    <!-- JS for Toggle menu -->
    <script>
        let MenuItems = document.getElementById("MenuItems");

        MenuItems.style.maxHeight = "0px";

      function menutoggle() {
        if (MenuItems.style.maxHeight === "0px") {
          MenuItems.style.maxHeight = "200px";
        } else {
          MenuItems.style.maxHeight = "0px";
        }
      }
    </script>
    <!--
js for toggle form -->
    <script>
        let LoginForm = document.getElementById("LoginForm");
        let RegForm = document.getElementById("RegForm");
        let indicator = document.getElementById("indicator");

        function register() {
        RegForm.style.transform = "translateX(0px)";
        LoginForm.style.transform = "translateX(0px)";
        indicator.style.transform = "translateX(100px)";
      }

      function login() {
        RegForm.style.transform = "translateX(300px)";
        LoginForm.style.transform = "translateX(300px)";
        indicator.style.transform = "translateX(0px)";
      }
    </script>
  </body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Product Detail{% endblock %}

{% block content %}
   <!-- Cart Items Details -->
    <div class="small-container cart-page">
    {% if cart.empty == False %}
      <table>
        <tr>
          <th>Product</th>
          <th>Quantity</th>
          <th>Subtotal</th>
        </tr>

          {% for item in cart %}
              {% with toy=item.product %}
        <tr>
          <td>
            <div class="cart-info">
              <img src="{{toy.image.url}}" alt="" />
              <div>
                <p>{{ toy.name }}</p>
                <small>Price: ${{ item.price }}</small>
                <br />
                <a href="{% url 'remove' toy.id %}">Remove</a>
              </div>
            </div>
          </td>
          <td>
              <form action="{% url 'add' toy.id %}" method="post">
                  {% csrf_token %}

              <input name="quantity" type="number" max="{{ toy.count }}" min="1" value="{{item.quantity}}" />
              <input type="hidden" name="update" value="True" id="id_update">
              <input class="btn" type="submit" value="Update">

              </form>
          </td>
          <td>${{ item.total_price }}</td>
        </tr>
        {% endwith %}
        {% endfor %}


      </table>

      <div class="total-price">
        <table>
          <tr>
            <td>Total</td>
            <td>${{cart.get_total_price}}</td>

          </tr>
        </table>

      </div>
    <a class="btn"  href="{% url 'checkout' %}">Create order</a>
    <a class="btn"  href="{% url 'delete_all' %}">Delete all</a>
        <a class="btn"  href="{% url 'catalog' %}">Choose more</a>

    {% else %}
        <a class="btn"  href="{% url 'catalog' %}">Add to cart toys</a>
    {% endif %}
    </div>
{% endblock content %}

templates/catalog.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Catalog{% endblock %}

{% block content %}

    <div class="small-container">
      <div class="row row-2">
        {% if type_toy is not None %}
        <h2>{{ type_toy }}</h2>
            {% else %}
            <h2>All toys</h2>
        {% endif %}
            <section>
              <h2>Categories</h2>
              <a href="{% url 'catalog'  %}"><p>All</p></a>
              {%for type in types_toy %}
               <a href="{% url 'filter' type.slug %}"><p>{{type.name}}</p></a>
              {% endfor %}
            </section>

      </div>

      <div class="row">
          {%for toy in toys %}
              <a href="{{toy.get_absolute_url}}" class="without_style">
        <div class="col-4">
          <img src="{{toy.image.url}}" alt="" width="50px" height="200px"/>
          <h4>{{toy.name}}</h4>
          <p>${{toy.price}}</p>
        </div>
              </a>
          {% endfor %}
        </div>



    </div>
{#    <div class="page-btn" >#}
{#  	<span id ="btnMore">Load more</span>#}
{#    </div>#}

    <script src="{% static 'js/more_guide.js' %}"></script>
    <script src="{% static 'js/jquery.vide.js' %}"></script>
{% endblock content %}

templates/change_password.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Change Password{% endblock %}

{% block content %}

   <div class="account-page">
      <div class="container">
        <div class="row">
          <div class="col-2">
            <img src="{% static 'images/image1.png' %}" width="100%" />
          </div>
          <div class="col-2">
            <div class="form-container">
              <div class="form-btn">
                <span>Change Password</span>
              </div>
              <form action=" " method="post" name="form">
                  {% csrf_token %}
                <input type="password" placeholder="Old Password" name="old_password"  required/>
                <input type="password" placeholder="New Password" name="new_password1" required/>
                <input type="password" placeholder="Repeat New Password" name="new_password2" required/>
                <button type="submit" class="btn">Change</button>
              </form>

            </div>
          </div>
        </div>
      </div>
    </div>


{% endblock %}

templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Checkout{% endblock %}



{% block content %}
<link rel="stylesheet" href="{% static 'css/checkout.css' %}" />
<section>



<div class="account-page">
      <div class="container">
        <div class="row">
          <div class="col-2">
            <img src="{% static 'images/image1.png' %}" width="100%" />
          </div>
          <div class="col-2">

            <div class="form-container-delivery">
              <div class="form-btn">
                <span>Indicate where to deliver</span>

                  </div>

<form action = "" method="post">
  {% csrf_token %}
  <input type="text" name="phone" maxlength="200" required id="id_phone" placeholder="Phone">
  <input type="text" name="address" maxlength="200" required id="id_address" placeholder="Address">
<input type="submit" class="btn" value="Confirm">
</form>
       </div>
          </div>
        </div>
      </div>
    </div>
</section>
{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Product Detail{% endblock %}

{% block content %}
<!-- Single Products Detail -->
    <div class="small-container single-product">
      <div class="row">
        <div class="col-2">
          <img src="{{toy.image.url}}" width="100%" id="ProductImg" />

        </div>
        <div class="col-2">
          <p>{{ toy.material.name }} {{ toy.color }}</p>
          <h2>{{ toy.name }}</h2>
          <h4>${{ toy.price }}</h4>
            <h4>Available: {{ toy.count }}</h4>
            {% if user.is_authenticated %}
            <form action="{% url 'add' id=toy.id %}" method="post">
                <input type="number" name="quantity" max="{{ toy.count }}" min="1" value="1" />
{#                <a href="" >Add to Cart</a>#}
                {% csrf_token %}
                <input type="submit" class="btn" value="Add to cart">
            </form>

            {% else %}
    <a href="{% url 'login' %}"> Log In, Please</a>
    {% endif %}
          <h3>Toy Details</h3>
          <br />
            <p>
             Size: {{ toy.size }}
          </p>
          <p>
              {{ toy.description }}
          </p>
        </div>
      </div>
    </div>

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Home{% endblock %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<div class="row">
          <div class="col-2">
            <h1>
              Give your toy<br />
              a new Knitted Style!
            </h1>
            <p>
              feel yourself child
            </p>
            <a href="{% url 'catalog' %}" class="btn">Explore Now &#8594;</a>
          </div>
          <div class="col-2">
            <img src="{% static 'images/image1.png' %}" alt="" />
          </div>
        </div>
      </div>
    </div>
{% endblock %}

templates/returned_receipt.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Success{% endblock %}



{% block content %}

    <section>



<div class="account-page">
      <div class="container">
        <div class="row">
          <div class="col-2">
            <img src="{% static 'images/image1.png' %}" width="100%" />
          </div>
          <div class="col-2">
            Your order number: {{order}}
          </div>
        </div>
      </div>
    </div>
</section>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Signup{% endblock %}

{% block content %}

    <div class="account-page">
      <div class="container">
        <div class="row">
          <div class="col-2">
            <img src="{% static 'images/image1.png' %}" width="100%" />
          </div>
          <div class="col-2">
            <div class="form-container" margin-top="10px">
              <div class="form-btn">
                <span>Sign Up</span>
              </div>
              <form action=" " method="post" name="form">
                  {% if form.errors %}
                    {{form.errors}}
                    {% endif %}
                  {% csrf_token %}
                <input type="text" placeholder="Username"  name="username" required />
                <input type="text" placeholder="First Name"  name="first_name" required />
                <input type="text" placeholder="Last Name"  name="last_name" required />
                <input type="email" placeholder="Email" name="email" required/>
                <input type="password" placeholder="Password" name="password1" required/>
                <input type="password" placeholder="Repeat Password" name="password2" required/>

                <button type="submit" class="btn">Sign Up</button>
                <a href = "/accounts/password_reset/"> <br>Forgot Password  |</a>
                  <a href = "{% url 'login' %}">Log In</a>
              </form>

            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}